### ISSUE TITLE
fix formatting

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx-www#3]
looks like the final version as served by github is missing some css or something.
compare to what i see from running the site locally to what we actually have:
![screen shot 2017-08-21 at 11 06 41 am](https://user-images.githubusercontent.com/963093/29525560-1cbdcf9e-8661-11e7-94f1-83313dea563c.png)
![screen shot 2017-08-21 at 11 06 53 am](https://user-images.githubusercontent.com/963093/29525559-1cbb5ed0-8661-11e7-930d-4597a4dde121.png)

**Comment by scottdraves** [comment]
maybe some difference between the node packages we are downloading and what github uses in production?

**Comment by jszalek** [comment]
@scottdraves Styling is fixed. The problem was with additional path '/beakerx-www/' in our url.
I set 'baseurl' parameter in config and edited url for css link (I'm not sure if this is elegant solution).
